### PR TITLE
Fix up the way Middleman is registered

### PR DESCRIPTION
**Pull request by edtjones**
Hi there,

I couldn't get this gem working until I made this change :-)

### CODE REVIEW

**Comment by 256dpi** [comment]
Thanks a lot! Does this mean that this gem is now compatible with Middleman v4?

**Comment by edtjones** [comment]
I think so!

## 

Sent from my phone: please forgive the brevity.

Ed Jones

**Comment by 256dpi** [comment]
FYI: I cut a new gem release that also uses the most recent lunr.js version available.

**Comment by edtjones** [comment]
Nice work. Glad I could help :-)

## 

Sent from my phone: please forgive the brevity.

Ed Jones

**Pull request merged**
